---
title: "Computational Therapeutic Screen Plotting"
author: "Brendan Ball"
date: "2024-08-03"
output: html_document
---

This code is used to make the figures for the computational therapeutic screening portion of the Cross-Disease Paper

```{r Drug List and Orange Book Pre-Processing}
drugdat <- read.csv ("PC2_alldrugs_rho.csv")
# JUN 2024 Orange Book Edition Accessed on Aug 2024, "https://www.fda.gov/media/71494/download?attachment"
orangebook <- read.csv ("OrangeBook_JUN2024.csv")

# Additional data frame filtered by over-the-counter drugs only
orangebookOTC <- orangebook %>%
  filter(str_detect(ApprovedDrug, "\\(OTC\\)"))

# Screen for FDA approved drugs in the Orange Book
drugdat <- drugdat %>%
  mutate(FDAapproval = sapply(tolower(drug), function(d) any(str_detect(tolower(orangebook$ApprovedDrug), d))))
# Screen for OTC drugs
drugdat <- drugdat %>%
  mutate(OTCstatus = sapply(tolower(drug), function(d) any(str_detect(tolower(orangebookOTC$ApprovedDrug), d))))
# Pull out drugs that are FDA approved
drugdatFDAapproved <- drugdat[grepl("TRUE", drugdat$FDAapproval),]
# Pull out drugs that are over-the-counter
drugdatOTC <- drugdat[grepl("TRUE", drugdat$OTCstatus),]
```

```{r Drug and Ranks Plots}
#svg('drugrank_all.svg', width = 4, height = 4)
# Plot all drugs and their respective ranks
ggplot(drugdat, aes(x = rank, y = spearmans_rho)) +
  geom_point(color = "black", size = 1.0) +
  labs(x = "Rank",
       y = "Spearman's Rho") +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black") +
  theme_bw() + 
  theme(panel.grid = element_blank()) +
  scale_x_continuous(limits = c(0, 1400), breaks = seq(0, 1400, by = 200)) +
  scale_y_continuous(limits = c(-0.6, 0.6)) + 
  theme(aspect.ratio = 1)
#dev.off()

#svg('drugrank_FDAapproved.svg', width = 4, height = 4)
# Plot drugs approved by the FDA in the orange book
ggplot(drugdatFDAapproved, aes(x = rank, y = spearmans_rho)) +
  geom_point(color = "black", size = 1.0) +
  labs(x = "Rank",
       y = "Spearman's Rho") +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black") +
  theme_bw() + 
  theme(panel.grid = element_blank()) +
  scale_x_continuous(limits = c(0, 1400), breaks = seq(0, 1400, by = 200)) +
  scale_y_continuous(limits = c(-0.6, 0.6)) + 
  theme(aspect.ratio = 1)
#dev.off()

#svg('drugrank_overthecounter.svg', width = 4, height = 4)
# Plot drugs approved over-the-counter in the orange book
ggplot(drugdatOTC, aes(x = rank, y = spearmans_rho)) +
  geom_point(color = "black", size = 1.0) +
  labs(x = "Rank",
       y = "Spearman's Rho") +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black") +
  theme_bw() + 
  theme(panel.grid = element_blank()) +
  scale_x_continuous(limits = c(0, 1400), breaks = seq(0, 1400, by = 200)) +
  scale_y_continuous(limits = c(-0.6, 0.6)) + 
  theme(aspect.ratio = 1)
#dev.off()
```

```{r Labeling the Plots with the Drug Names}
# Plot with labeling the FDA approved drugs
ggplot(drugdatFDAapproved, aes(x = rank, y = spearmans_rho)) +
  geom_point(color = "black", size = 1.0) +
  geom_text_repel(aes(label = ifelse(rank < 20 | rank > 1350, drug, "")), 
                  size = 2.5, 
                  max.overlaps = Inf) + 
  geom_hline(yintercept = 0, linetype = "dashed", color = "black") +
  labs(x = "Rank",
       y = "Spearman's Rho") +
  theme_bw() + 
  theme(panel.grid = element_blank()) +
  scale_x_continuous(limits = c(0, 1400), breaks = seq(0, 1400, by = 200)) +
  scale_y_continuous(limits = c(-0.6, 0.6)) + 
  theme(aspect.ratio = 1)

# Plot with labeling the drugs on over-the-counter
ggplot(drugdatOTC, aes(x = rank, y = spearmans_rho)) +
  geom_point(color = "black", size = 1.0) +
  geom_text_repel(aes(label = ifelse(rank < 300 | rank > 800, drug, "")), 
                  size = 2.5, 
                  max.overlaps = Inf) + 
  geom_hline(yintercept = 0, linetype = "dashed", color = "black") +
  labs(x = "Rank",
       y = "Spearman's Rho") +
  theme_bw() + 
  theme(panel.grid = element_blank()) +
  scale_x_continuous(limits = c(0, 1400), breaks = seq(0, 1400, by = 200)) +
  scale_y_continuous(limits = c(-0.6, 0.6)) + 
  theme(aspect.ratio = 1)
```

```{r Export the drug list}
# Save FDA-approved data
#write.csv(drugdatFDAapproved, "drugdatFDAapproved_list.csv")
```




